module.exports.post_login = function(request, result){
	var text = 'Welcome, ' + getName(request);
	sendBody(text, result);
};


function getName(request){
	var userName = request.param('user');
	return userName;
}

/*function sendBody(text, result){
	    var html = '<!DOCTYPE html>\n'
	        + '<html lang="en-US">\n'
	        // + '<head>\n'
	        // + ' <meta charset="UTF-8">\n'
	        // + ' <title>Form Examples</title>\n'
	        // + '</head>\n'
	        
	        + '<body style="background-color:powderblue;">\n'
	        // + ' ' + text + '\n' // insert the body text
			// + '<h1 class="h1">HOME PAGE AFTER LOGIN</h1>'
	        + '<h2 style="text-align: center;margin-top: 20%">'+ text +'\n'
	        + '</body>\n'
	        + '</html>\n';
	    result.send(html);
	}
	*/


/*
function sendBody(text, result){
	    var html =
		'<!DOCTYPE html>                                                                                                                                                                      \n'
		+'<html>                                                                                                                                                                              \n'
		+'<head>                                                                                                                                                                              \n'
		+'<meta name="viewport" content="width=device-width, initial-scale=1">                                                                                                                \n'
		+'<style> * { box-sizing: border-box;}                                                                                                                                                \n'
		+'                                                                                                                                                                                    \n'
		+'#input {                                                                                                                                                                            \n'
		+'  background-position: 10px 10px;                                                                                                                                                   \n'
		+'  background-repeat: no-repeat;                                                                                                                                                     \n'
		+'  width: 100%;                                                                                                                                                                      \n'
		+'  font-size: 16px;                                                                                                                                                                  \n'
		+'  padding: 12px 20px 12px 40px;                                                                                                                                                     \n'
		+'  border: 1px solid #ddd;                                                                                                                                                           \n'
		+'  margin-bottom: 12px;                                                                                                                                                              \n'
		+'}                                                                                                                                                                                   \n'
		+'                                                                                                                                                                                    \n'
		+'#table {                                                                                                                                                                            \n'
		+'  border-collapse: collapse;                                                                                                                                                        \n'
		+'  width: 100%;                                                                                                                                                                      \n'
		+'  border: 1px solid #ddd;                                                                                                                                                           \n'
		+'  font-size: 18px;                                                                                                                                                                  \n'
		+'}                                                                                                                                                                                   \n'
		+'                                                                                                                                                                                    \n'
		+'#table th, #myTable td {                                                                                                                                                            \n'
		+'  text-align: left;                                                                                                                                                                 \n'
		+'  padding: 12px;                                                                                                                                                                    \n'
		+'}                                                                                                                                                                                   \n'
		+'                                                                                                                                                                                    \n'
		+'#table tr {                                                                                                                                                                         \n'
		+'  border-bottom: 1px solid #ddd;                                                                                                                                                    \n'
		+'}                                                                                                                                                                                   \n'
		+'                                                                                                                                                                                    \n'
		+'#table tr.header, #myTable tr:hover {                                                                                                                                               \n'
		+'  background-color: #f1f1f1;                                                                                                                                                        \n'
		+'}                                                                                                                                                                                   \n'
		+'</style>                                                                                                                                                                            \n'
		+'</head>                                                                                                                                                                             \n'
		+'<body>                                                                                                                                                                              \n'
		+'                                                                                                                                                                                    \n'
		+'<h2>Learn About Climate Change</h2>                                                                                                                                                 \n'
		+'                                                                                                                                                                                    \n'
		+'<input type="text" id="input" onkeyup="myFunction()" placeholder="Search for articles.." title="Type a name">                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'<table id="table">                                                                                                                                                                  \n'
		+'  <tr class="header">                                                                                                                                                               \n'
		+'    <th style="width:60%;">Article Name</th>                                                                                                                                        \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'    <td>                                                                                                                                                                            \n'
		+'            <a href="https://www.bloomberg.com/news/articles/2019-09-18/investors-managing-16-trillion-demand-action-on-deforestation">                                             \n'
		+'                <div style="height:100%;width:100%">                                                                                                                                \n'
		+'                        Investors With $16 Trillion Want Deforestation Action                                                                                                       \n'
		+'                </div>                                                                                                                                                              \n'
		+'              </a>                                                                                                                                                                  \n'
		+'    </td>                                                                                                                                                                           \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://news.mongabay.com/2019/09/brazilian-amazon-fires-scientifically-linked-to-2019-deforestation-report/ ">                                            \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Brazilian Amazon fires scientifically linked to 2019 deforestation: report                                                                              \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://e360.yale.edu/features/will-deforestation-and-warming-push-the-amazon-to-a-tipping-point ">                                                        \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Will Deforestation and Warming Push the Amazon to a Tipping Point?                                                                                      \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://science.sciencemag.org/content/365/6456/853 ">                                                                                                     \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Amazon fires clearly linked to deforestation, scientists say                                                                                            \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://www.nationalgeographic.com/environment/2019/08/wildfires-in-amazon-caused-by-deforestation/ ">                                                     \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            The Amazon is burning at record ratesâ€”and deforestation is to blame                                                                                   \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://truthout.org/articles/10-things-you-need-to-know-about-the-fires-in-the-amazon/">                                                                  \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            10 Things You Need to Know About the Fires in the Amazon                                                                                                \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://news.mongabay.com/2019/09/amazon-deforestation-and-development-heighten-amazon-fire-risk-study/ ">                                                 \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Amazon deforestation and development heighten Amazon fire risk: study                                                                                   \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://www.latimes.com/opinion/editorials/la-ed-climate-change-crisis-global-warming-part-1-story.html ">                                                 \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Editorial: Climate change is already here. 2020 could be your last chance to stop an apocalypse                                                         \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://www.scientificamerican.com/article/global-warming-has-been-influencing-drought-for-a-century/ ">                                                   \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Global Warming Has Been Influencing Drought for a Century                                                                                               \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://www.usatoday.com/story/news/nation/2019/03/15/california-drought-free-after-7-years-dry-conditions-remain/3168753002/ ">                           \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Mediterranean climate: California drought ends after more than 7 years, but dry conditions will return                                                 \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://www.business-standard.com/article/pti-stories/poor-countries-will-need-to-increase-carbon-footprint-to-address-hunger-study-119091700109_1.html "> \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                            \n'
		+'                            Developing nations should increase carbon footprint to tackle hunger: Study                                                                             \n'
		+'                    </div>                                                                                                                                                          \n'
		+'                  </a>                                                                                                                                                              \n'
		+'        </td>                                                                                                                                                                       \n'
		+'                                                                                                                                                                                    \n'
		+'  </tr>                                                                                                                                                                             \n'
		+'  <tr>                                                                                                                                                                              \n'
		+'        <td>                                                                                                                                                                        \n'
		+'                <a href="https://www.manilatimes.net/2019/09/19/opinion/columnists/topanalysis/poor-countries-must-increase-carbon-footprint-to-address-hunger-says-study/618571/ ">\n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            Poor countries must increase carbon footprint to address hunger, says study                                                                                \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://www.wsj.com/articles/how-to-get-rid-of-carbon-emissions-pay-farmers-to-bury-them-11568211869 ">                                                       \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            How to Get Rid of Carbon Emissions: Pay Farmers to Bury Them                                                                                               \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://www.scientificamerican.com/article/climate-change-is-having-widespread-health-impacts/ ">                                                             \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            Climate Change Is Having Widespread Health Impacts                                                                                                         \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://www.truthdig.com/articles/climate-change-is-already-hitting-europe-harder-than-anyone-expected/ ">                                                    \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            Climate Change Is Already Hitting Europe Harder Than Anyone Expected                                                                                       \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://www.nature.com/immersive/d41586-019-02711-4/index.html ">                                                                                             \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            The hard truths of climate change â€” by the numbers                                                                                                       \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://eos.org/articles/global-warming-is-conquering-the-vikings ">                                                                                          \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            Global Warming Is Conquering the Vikings                                                                                                                   \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://insideclimatenews.org/news/03092019/hurricane-dorian-climate-change-stall-record-wind-speed-rainfall-intensity-global-warming-bahamas ">              \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            Why Are Hurricanes Like Dorian Stalling, and Is Global Warming Involved?                                                                                   \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'  <tr>                                                                                                                                                                                 \n'
		+'        <td>                                                                                                                                                                           \n'
		+'                <a href="https://www.scientificamerican.com/article/earths-orbital-shifts-may-have-triggered-ancient-global-warming/ ">                                                \n'
		+'                    <div style="height:100%;width:100%">                                                                                                                               \n'
		+'                            Earthâ€™s Orbital Shifts May Have Triggered Ancient Global Warming                                                                                         \n'
		+'                    </div>                                                                                                                                                             \n'
		+'                  </a>                                                                                                                                                                 \n'
		+'        </td>                                                                                                                                                                          \n'
		+'                                                                                                                                                                                       \n'
		+'  </tr>                                                                                                                                                                                \n'
		+'                                                                                                                                                                                       \n'
		+'</table>                                                                                                                                                                               \n'
		+'                                                                                                                                                                                       \n'
		+'<script>                                                                                                                                                                               \n'
		+'function myFunction() {                                                                                                                                                                \n'
		+'  var input, filter, table, tr, td, i, textValue;                                                                                                                                      \n'
		+'  input = document.getElementById("input");                                                                                                                                            \n'
		+'  filter = input.value.toUpperCase();                                                                                                                                                  \n'
		+'  table = document.getElementById("table");                                                                                                                                            \n'
		+'  tr = table.getElementsByTagName("tr");                                                                                                                                               \n'
		+'  for (i = 0; i < tr.length; i++) {                                                                                                                                                    \n'
		+'    td = tr[i].getElementsByTagName("td")[0];                                                                                                                                          \n'
		+'    if (td) {                                                                                                                                                                          \n'
		+'      textValue = td.textContent || td.innerText;                                                                                                                                      \n'
		+'      if (textValue.toUpperCase().indexOf(filter) > -1) {                                                                                                                              \n'
		+'        tr[i].style.display = "";                                                                                                                                                      \n'
		+'      } else {                                                                                                                                                                         \n'
		+'        tr[i].style.display = "none";                                                                                                                                                  \n'
		+'      }                                                                                                                                                                                \n'
		+'    }                                                                                                                                                                                  \n'
		+'  }                                                                                                                                                                                    \n'
		+'}                                                                                                                                                                                      \n'
		+'</script>\n'
		+'</body>\n'                                                                                                                                                                             
		+'</html>';                                                                                                                                                                            
		                                                                                                                                                                                        
		result.send(html);
}
*/